services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    environment:
      - SA_PASSWORD=YourStrong!Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - "14330:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - keycloak-sql-dab-network

  dab:
    build:
      context: ./DAB
    container_name: dab
    depends_on:
      - mssql
    ports:
      - "5000:5000"
      - "5001:5001"
    env_file:
      - ./.env
    volumes:
      - ./dab-config.json:/App/dab-config.json:ro
    networks:
      - keycloak-sql-dab-network

  keycloak:
    build:
      context: ./keycloak
    container_name: keycloak
    ports:
      - "8443:8443"
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - keycloak-sql-dab-network

volumes:
  mssql-data:
  keycloak_data:

networks:
  keycloak-sql-dab-network:
    driver: bridge